- platform: rocketchat
  name: rocketchat_fyrabe
  url: !secret rocketchat_url
  username: !secret rocketchat_username
  password: !secret rocketchat_password
  room: fyrabe
- platform: rocketchat
  name: rocketchat_3ddruck
  url: !secret rocketchat_url
  username: !secret rocketchat_username
  password: !secret rocketchat_password
  room: 3d-druck
- platform: twitter
  name: twitter_fyrabe
  consumer_key: !secret twitter_consumer_key
  consumer_secret: !secret twitter_consumer_secret
  access_token: !secret twitter_access_token
  access_token_secret: !secret twitter_access_token_secret
