- platform: template
  sensors:
    mystrom001:
      friendly_name: "Current Power"
      unit_of_measurement: "W"
      value_template: "{{ state_attr('switch.mystrom001', 'current_power_w') }}"
    mystrom002:
      friendly_name: "Current Power"
      unit_of_measurement: "W"
      value_template: "{{ state_attr('switch.mystrom002', 'current_power_w') }}"
    mystrom003:
      friendly_name: "Current Power"
      unit_of_measurement: "W"
      value_template: "{{ state_attr('switch.mystrom003', 'current_power_w') }}"
    mystrom004:
      friendly_name: "Current Power"
      unit_of_measurement: "W"
      value_template: "{{ state_attr('switch.mystrom004', 'current_power_w') }}"
    mystrom005:
      friendly_name: "Current Power"
      unit_of_measurement: "W"
      value_template: "{{ state_attr('switch.mystrom005', 'current_power_w') }}"
    mystrom006:
      friendly_name: "Current Power"
      unit_of_measurement: "W"
      value_template: "{{ state_attr('switch.mystrom006', 'current_power_w') }}"
    mystrom007:
      friendly_name: "Current Power"
      unit_of_measurement: "W"
      value_template: "{{ state_attr('switch.mystrom007', 'current_power_w') }}"
    mystrom008:
      friendly_name: "Current Power"
      unit_of_measurement: "W"
      value_template: "{{ state_attr('switch.mystrom008', 'current_power_w') }}"
    mystrom009:
      friendly_name: "Current Power"
      unit_of_measurement: "W"
      value_template: "{{ state_attr('switch.mystrom009', 'current_power_w') }}"
    mystrom010:
      friendly_name: "Current Power"
      unit_of_measurement: "W"
      value_template: "{{ state_attr('switch.mystrom010', 'current_power_w') }}"
    mystrom011:
      friendly_name: "Current Power"
      unit_of_measurement: "W"
      value_template: "{{ state_attr('switch.mystrom011', 'current_power_w') }}"
    mystrom012:
      friendly_name: "Current Power"
      unit_of_measurement: "W"
      value_template: "{{ state_attr('switch.mystrom012', 'current_power_w') }}"
