- platform: flux
  lights:
  - light.bar_bulb_1
  - light.bar_bulb_2
  - light.bar_bulb_3
  - light.bar_bulb_4
  - light.bar_bulb_5
  name: Bar Automatic Lighting
  start_time: '06:00'
  start_colortemp: 3800
  sunset_colortemp: 2300
  mode: mired
  transition: 1
  interval: 1
- platform: mqtt
  name: sonoff1688
  state_topic: "be3/tux/projector/stat/POWER"
  command_topic: "be3/tux/projector/cmnd/POWER"
  availability_topic: "be3/tux/projector/tele/LWT"
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: sonoff5530
  state_topic: "be3/bar/coffee/stat/POWER"
  command_topic: "be3/bar/coffee/cmnd/POWER"
  availability_topic: "be3/bar/coffee/tele/LWT"
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mystrom
  host: 10.14.1.6
  name: systvscreen
- platform: mystrom
  host: 10.14.1.7
  name: kafiscreen
- platform: mystrom
  host: 10.14.1.17
  name: rubyscreen
- platform: mystrom
  host: 10.14.1.13
  name: gangscreen
- platform: mystrom
  host: 10.14.1.24
  name: swoascreen
- platform: mystrom
  host: 10.14.1.28
  name: druckerscreen
- platform: mystrom
  host: 10.14.1.21
  name: altekaffemaschine
- platform: mystrom
  host: 10.14.1.22
  name: apstandardt
- platform: mystrom
  host: 10.14.1.25
  name: wasserspender
- platform: mystrom
  host: 10.14.1.12
  name: drucker
- platform: mystrom
  host: 10.14.1.18
  name: bierkuehlschrank
- platform: mystrom
  host: 10.14.1.27
  name: apneuc
- platform: mystrom
  host: 10.14.1.11
  name: mikrowelleunten
- platform: mystrom
  host: 10.14.1.23
  name: mikrowelleoben
- platform: mystrom
  host: 10.14.1.19
  name: kaffeemuehle
- platform: mystrom
  host: 10.14.1.26
  name: apaltj
