- platform: mystrom
  host: 10.14.1.1
  name: mystrom001
- platform: mystrom
  host: 10.14.1.2
  name: mystrom002
- platform: mystrom
  host: 10.14.1.3
  name: mystrom003
- platform: mystrom
  host: 10.14.1.4
  name: mystrom004
- platform: mystrom
  host: 10.14.1.5
  name: mystrom005
- platform: mystrom
  host: 10.14.1.6
  name: mystrom006
- platform: mystrom
  host: 10.14.1.7
  name: mystrom007
- platform: mystrom
  host: 10.14.1.8
  name: mystrom008
- platform: mystrom
  host: 10.14.1.9
  name: mystrom009
- platform: mystrom
  host: 10.14.1.10
  name: mystrom010
- platform: mystrom
  host: 10.14.1.11
  name: mystrom011
- platform: mystrom
  host: 10.14.1.12
  name: mystrom012
