title: Puzzle
views:
  - badges:
      - entity: binary_sensor.beer_button
      - entity: counter.fyrabebier
        name: Fyrabebier Counter
      - entity: timer.fyrabe
        name: Fyrabebier Timer
      - entity: binary_sensor.shelly_1pm_b9849d_update
        name: Shelly 1PM B9849D Update
    cards:
      - entities:
          - entity: switch.shelly_1pm_b9849d
            name: Coffee Machine
            icon: 'mdi:coffee'
            state_color: true
          - entity: light.lvl3_bar
            icon: 'mdi:ceiling-light'
            name: Lights
          - entity: switch.mystrom004
            icon: 'mdi:speaker'
            name: Audio System
            state_color: true
          - entity: switch.mystrom003
            icon: 'mdi:television'
            name: Screen
            state_color: true
          - entity: binary_sensor.lvl3_bar_sensor_motion
            name: Motion Sensor
          - entity: sensor.lvl3_bar_sensor_temperature
            name: Temperature Sensor
          - entity: sensor.lvl3_bar_sensor_light_level
            name: Light Level Sensor
        show_header_toggle: false
        title: Lvl3 Bar
        type: entities
      - entities:
          - entity: switch.mystrom002
            icon: 'mdi:television'
            name: Screen
            state_color: true
        show_header_toggle: false
        title: Lvl3 Hallway
        type: entities
      - entities:
          - entity: switch.mystrom001
            icon: 'mdi:television'
            name: Screen
            state_color: true
        show_header_toggle: false
        title: Lvl3 /sys & /mid Office
        type: entities
      - entities:
          - entity: switch.mystrom005
            icon: 'mdi:television'
            name: Screen
            state_color: true
        show_header_toggle: false
        title: Lvl3 Piazza
        type: entities
      - entities:
          - entity: switch.mystrom006
            icon: 'mdi:television'
            name: Screen
            state_color: true
        show_header_toggle: false
        title: Lvl3 /dev/ruby Office
        type: entities
      - entities:
          - entity: switch.mystrom009
            icon: 'mdi:projector'
            name: Projector
            state_color: true
          - entity: switch.mystrom010
            icon: 'mdi:floor-lamp'
            name: Floor Lamp Front
            state_color: true
          - entity: switch.mystrom012
            icon: 'mdi:floor-lamp'
            name: Floor Lamp Back
            state_color: true
        show_header_toggle: false
        title: Lvl3 Tux Meeting Room
        type: entities
      - entities:
          - entity: switch.mystrom007
            icon: 'mdi:television'
            name: Screen Front
            state_color: true
          - entity: switch.mystrom008
            icon: 'mdi:television'
            name: Screen Back
            state_color: true
        show_header_toggle: false
        title: Lvl-1 /dev/tre Office
        type: entities
      - type: conditional
        conditions:
        - entity: binary_sensor.binary_command_sensor
          state: "on"
        card:
          type: entities
        entities:
        - entity: script.update_home_assistant
          name: Update Home Assistant
    icon: 'mdi:home-assistant'
    path: default_view
    title: Home
  - badges: []
    cards:
      - type: sensor
        entity: sensor.mystrom001
        name: Lvl3 /sys & /mid Office Screen
        icon: mdi:television
        graph: line
      - type: sensor
        entity: sensor.mystrom002
        name: Lvl3 Hallway Screen
        icon: mdi:television
        graph: line
      - type: sensor
        entity: sensor.mystrom003
        name: Lvl3 Bar Screen
        icon: mdi:television
        graph: line
      - type: sensor
        entity: sensor.mystrom004
        name: Lvl3 Bar Audio System
        icon: mdi:television
        graph: line
      - type: sensor
        entity: sensor.mystrom005
        name: Lvl3 Piazza Screen
        icon: mdi:television
        graph: line
      - type: sensor
        entity: sensor.mystrom006
        name: Lvl3 /dev/ruby Office Screen
        icon: mdi:television
        graph: line
      - type: sensor
        entity: sensor.mystrom007
        name: Lvl-1 /dev/tre Office Screen Front
        icon: mdi:television
        graph: line
      - type: sensor
        entity: sensor.mystrom008
        name: Lvl-1 /dev/tre Office Screen Back
        icon: mdi:television
        graph: line
      - type: sensor
        entity: sensor.mystrom009
        name: Lvl3 Tux Meeting Room Projector
        icon: mdi:projector
        graph: line
      - type: sensor
        entity: sensor.mystrom010
        name: Lvl3 Tux Meeting Room Floor Lamp Front
        icon: mdi:floor-lamp
        graph: line
      - type: sensor
        entity: sensor.mystrom011
        name: Lvl3 /sys & /mid Office Floor Lamp
        icon: mdi:floor-lamp
        graph: line
      - type: sensor
        entity: sensor.mystrom012
        name: Lvl3 Tux Meeting Room Floor Lamp Back
        icon: mdi:floor-lamp
        graph: line
      - entity: sensor.shelly_1pm_b9849d_power
        graph: line
        icon: 'mdi:coffee'
        name: Lvl3 Bar Coffee Machine
        type: sensor
    icon: 'mdi:gauge'
    path: power
    title: Power
