title: Puzzle Assistant
views:
- title: Puzzle
  icon: mdi:puzzle
  cards:
  - type: glance
    title: Bar
    entities:
    - entity: automation.automatic_bar_lighting
      name: Automatic Lighting
      icon: mdi:weather-sunset
    - entity: switch.mystrom3
      name: 'Kafi Screen'
      icon: mdi:television
  - type: glance
    title: Backoffice
    entities:
    - entity: light.sonoff1905
      name: Floor Lamp 1
      icon: mdi:floor-lamp
    - entity: input_boolean.sonoff1905_timebased_lighting
      name: Time-Based Lighting
      icon: mdi:clock-outline
    - entity: switch.mystrom2
      name: Eingang Screen 3. OG
      icon: mdi:television
  - type: glance
    title: /dev/tre
    entities:
    - entity: light.sonoff1645
      name: Floor Lamp 1
      icon: mdi:floor-lamp
    - entity: input_boolean.sonoff1645_timebased_lighting
      name: Time-Based Lighting
      icon: mdi:clock-outline
    - entity: switch.mystrom7
      name: Screen vorne
      icon: mdi:television
    - entity: switch.mystrom8
      name: Screen hinten
      icon: mdi:television
  - type: glance
    title: /dev/ruby
    entities:
    - entity: switch.mystrom6
      name: Ruby Screen
      icon: mdi:television
  - type: glance
    title: /sys & /mid
    entities:
    - entity: light.sonoff1911
      name: Floor Lamp 1
      icon: mdi:floor-lamp
    - entity: input_boolean.sonoff1911_timebased_lighting
      name: Time-Based Lighting
      icon: mdi:clock-outline
    - entity:  switch.mystrom1
      name: TV Screen
      icon: mdi:television
  - type: glance
    title: TUX
    entities:
    - entity: light.sonoff7461
      name: Floor Lamp 1
      icon: mdi:floor-lamp
    - entity: light.sonoff4126
      name: Floor Lamp 2
      icon: mdi:floor-lamp
    - entity: switch.sonoff1688
      name: Projector
      icon: mdi:projector
- title: Settings
  icon: mdi:settings
  cards:
  - type: light
    name: Bar Bulb 1
    entity: light.bar_bulb_1
  - type: light
    name: Bar Bulb 2
    entity: light.bar_bulb_2
  - type: light
    name: Bar Bulb 3
    entity: light.bar_bulb_3
  - type: light
    name: Bar Bulb 4
    entity: light.bar_bulb_4
  - type: light
    name: Bar Bulb 5
    entity: light.bar_bulb_5
- title: Energy
  icon: mdi:power-plug
  cards:
  - type: sensor
    name: Power Statistics
    unit: W
    entity: sensor.power_total
    graph: line
  - type: sensor
    entity: sensor.energy_total
    name: Energy Statistics
    unit: kWh
    graph: line
